name: github checkout action 
on: push 
jobs:
  action-demo:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: configure aws credentials 
        uses: aws-actions/configure-aws-credentials@v4 
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key-id: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }} 
          aws-region: ap-south-1
      - name: code should deploy to s3
        run : |
          aws s3 sync ./ s3://github-s3s/ \
          --exclude "*" \
          --include "index.html"
