name: Hell World
on: workflow_dispatch
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hell world
        run: |
          echo "this is line1"
          echo "this is line2"
          echo "${{ vars.my_name }}"
          echo "${{ secrets.docker_password }}"
          echo "${{pwd}}"
