name: Hello World 
on:
  push:
    - main
    - branch
    - 'releases/**'
  pull_request:
    - main
    - develop
    - 'releases/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build the job
        run: echo "build the job"
